cmake_minimum_required(VERSION 3.8)
project(aachen_rover)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch urdf worlds config DESTINATION share/${PROJECT_NAME})
install(PROGRAMS scripts/teleop_gui.py scripts/velocity_guard.py scripts/smoke_test.py DESTINATION lib/${PROJECT_NAME})
install(FILES scripts/control.py DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(control test/test_control.py)
endif()
ament_package()
